#!/usr/bin/env python3
"""
Gemini AI Advisor for Garissa Environmental Analysis
Generates actionable environmental advice and community alerts
"""
import google.generativeai as genai
from datetime import datetime
import pandas as pd


class GeminiAdvisor:
    """AI-powered environmental consulting using Google Gemini"""
    
    def __init__(self, api_key):
        """
        Initialize Gemini AI advisor
        
        Args:
            api_key: Google AI API key
        """
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel('gemini-pro')
        print("✅ Gemini AI initialized")
    
    def generate_advisory_report(self, camp_health_df):
        """
        Generate comprehensive environmental advisory report
        
        Args:
            camp_health_df: DataFrame with camp vegetation health statistics
            
        Returns:
            Markdown-formatted advisory report
        """
        print("🤖 Generating AI advisory report...")
        
        # Prepare data summary
        data_summary = self._format_data_summary(camp_health_df)
        
        prompt = f"""
You are an expert Environmental Consultant for Garissa County, Kenya, specializing in:
- Rangeland management for pastoralist communities
- Deforestation monitoring around refugee settlements
- Climate adaptation strategies for arid and semi-arid lands (ASAL)
- Community-based natural resource management

I am providing you with satellite-derived vegetation change data (NDVI) for refugee camp blocks in Garissa County.

**DATA INTERPRETATION:**
- NDVI (Normalized Difference Vegetation Index) measures vegetation health (greenness)
- NDVI Change = 2025 NDVI - 2024 NDVI
- **Negative values** indicate vegetation loss (deforestation/land degradation)
- **Positive values** indicate vegetation recovery/growth
- Values near zero indicate stable conditions

**VEGETATION CHANGE DATA:**
{data_summary}

**YOUR TASK:**
Generate a comprehensive advisory report in Markdown format with the following sections:

## 1. Executive Summary
Provide a 3-sentence overview of the overall ecological status.

## 2. Critical Areas
Identify which camp blocks are experiencing the most severe degradation. Explain why this matters for the community.

## 3. Root Cause Analysis
Explain potential drivers of the observed changes (e.g., firewood collection, overgrazing, refugee population pressure, seasonal rainfall patterns).

## 4. Actionable Recommendations
Provide 5 specific, practical recommendations for:
- Garissa County Government
- Community Grazing Committees
- UNHCR/Humanitarian Partners
- Local Chiefs (Nyumba Kumi)

## 5. Monitoring Plan
Suggest key indicators to track over the next 3 months.

## 6. Community Communication
Draft a simple message (in both English and Swahili) that can be shared with community leaders.

**IMPORTANT:** Your recommendations should be:
- Culturally sensitive to pastoralist livelihoods
- Practical and low-cost
- Based on successful ASAL interventions
- Aligned with Kenya's Climate Change Act 2016

Generate the report now:
"""
        
        try:
            response = self.model.generate_content(prompt)
            report = response.text
            
            # Add header with metadata
            full_report = f"""# Garissa Sentinel - AI Environmental Advisory Report
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**System:** Garissa Sentinel Digital Twin  
**AI Model:** Google Gemini Pro  
**Region:** Garissa County, Kenya

---

{report}

---

## Technical Appendix

### Data Sources
- **Satellite Imagery:** Copernicus Sentinel-2 (10-30m resolution)
- **Analysis Period:** 2024 vs 2025
- **Vegetation Index:** NDVI (Normalized Difference Vegetation Index)
- **Population Data:** WorldPop 2020

### Methodology
1. **Cloud Filtering:** Only images with <20% cloud cover used
2. **Temporal Aggregation:** Median composite to reduce noise
3. **Change Detection:** Simple difference (2025 NDVI - 2024 NDVI)
4. **Spatial Analysis:** Per-camp block statistics extraction

### Limitations
- NDVI cannot distinguish between natural and human-induced changes
- Seasonal rainfall variations may affect results
- Small-scale changes (<30m) may not be detected
- Cloud cover may limit data availability in wet seasons

---

*This report was generated by AI and should be reviewed by environmental specialists before implementation.*
"""
            
            print("✅ AI report generated successfully")
            return full_report
            
        except Exception as e:
            print(f"❌ Error generating AI report: {e}")
            return f"# Error Generating Report\n\nError: {e}"
    
    def generate_sms_alerts(self, camp_health_df, threshold=-0.1):
        """
        Generate SMS-length alerts for areas with critical degradation
        
        Args:
            camp_health_df: DataFrame with vegetation statistics
            threshold: NDVI change threshold for alert (default -0.1)
            
        Returns:
            List of SMS alert strings (<160 characters each)
        """
        print(f"📱 Generating SMS alerts (threshold: {threshold})...")
        
        alerts = []
        
        # Filter camps with significant degradation
        if 'mean' in camp_health_df.columns and 'camp_name' in camp_health_df.columns:
            critical_camps = camp_health_df[camp_health_df['mean'] < threshold]
            
            for _, row in critical_camps.iterrows():
                camp_name = row.get('camp_name', 'Unknown')
                ndvi_change = row.get('mean', 0)
                
                # English alert
                alert_en = f"ALERT: {camp_name} camp shows vegetation loss ({ndvi_change:.2f}). Reduce firewood collection, protect young trees."
                alerts.append(alert_en[:160])  # Truncate to 160 chars
                
                # Swahili alert
                alert_sw = f"TAHADHARI: Kambi ya {camp_name} ina upotevu wa mimea ({ndvi_change:.2f}). Punguza ukusanyaji wa kuni, linda miti michanga."
                alerts.append(alert_sw[:160])
        
        if alerts:
            print(f"✅ Generated {len(alerts)} SMS alerts")
        else:
            print("ℹ️  No critical degradation detected - no alerts needed")
        
        return alerts
    
    def _format_data_summary(self, df):
        """Format DataFrame for AI consumption"""
        if df.empty:
            return "No data available"
        
        # Select relevant columns
        cols = ['camp_name', 'mean', 'stdDev', 'min', 'max'] if 'camp_name' in df.columns else df.columns.tolist()
        summary_df = df[cols] if all(c in df.columns for c in cols) else df
        
        # Format as markdown table
        return summary_df.head(20).to_markdown(index=False)


if __name__ == "__main__":
    # Test with sample data
    sample_data = pd.DataFrame({
        'camp_name': ['Hagadera', 'Dagahaley', 'Ifo'],
        'mean': [-0.15, -0.05, 0.02],
        'stdDev': [0.08, 0.06, 0.05],
        'min': [-0.35, -0.20, -0.10],
        'max': [0.05, 0.10, 0.15]
    })
    
    # Note: Using test API key - replace with actual key
    advisor = GeminiAdvisor(api_key="AIzaSyDDZludrLe0owCB3jFvPWSp8b3ZBx5hBmQ")
    
    # Test report generation
    report = advisor.generate_advisory_report(sample_data)
    print("\n" + "="*60)
    print("SAMPLE REPORT:")
    print("="*60)
    print(report[:500] + "...\n")
    
    # Test SMS generation
    alerts = advisor.generate_sms_alerts(sample_data)
    print("\n" + "="*60)
    print("SAMPLE SMS ALERTS:")
    print("="*60)
    for alert in alerts:
        print(f"- {alert}")
