#!/usr/bin/env python3
"""
Geofencing Engine for Safe Grazing Zones
Exports spatial data in multiple formats: GeoJSON, KML, Shapefile, CSV
"""
import json
from pathlib import Path
import simplekml
import shapefile as shp
from datetime import datetime


class GeofencingEngine:
    """Handles automatic geofencing and multi-format spatial exports"""
    
    def __init__(self, output_dir):
        """
        Initialize the geofencing engine
        
        Args:
            output_dir: Directory to save output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def export_geojson(self, ee_feature_collection, filename):
        """
        Export to GeoJSON format (for web maps and JavaScript)
        
        Args:
            ee_feature_collection: Earth Engine FeatureCollection data (as dict)
            filename: Output filename (without extension)
        """
        output_file = self.output_dir / f"{filename}.geojson"
        
        # Convert EE format to standard GeoJSON
        geojson_data = {
            "type": "FeatureCollection",
            "features": ee_feature_collection.get('features', []),
            "metadata": {
                "generated_at": datetime.now().isoformat(),
                "system": "Garissa Sentinel",
                "description": "Safe grazing zones for pastoralist communities"
            }
        }
        
        with open(output_file, 'w') as f:
            json.dump(geojson_data, f, indent=2)
        
        print(f"✅ GeoJSON exported: {output_file}")
        return output_file
    
    def export_kml(self, ee_feature_collection, filename):
        """
        Export to KML format (for Google Earth)
        
        Args:
            ee_feature_collection: Earth Engine FeatureCollection data (as dict)
            filename: Output filename (without extension)
        """
        output_file = self.output_dir / f"{filename}.kml"
        
        kml = simplekml.Kml()
        kml.document.name = "Garissa Safe Grazing Zones"
        kml.document.description = f"Generated by Garissa Sentinel on {datetime.now().strftime('%Y-%m-%d')}"
        
        features = ee_feature_collection.get('features', [])
        
        for i, feat in enumerate(features):
            geom = feat.get('geometry', {})
            geom_type = geom.get('type', '')
            coords = geom.get('coordinates', [])
            
            if geom_type == 'Polygon' and coords:
                # Extract outer ring coordinates
                outer_ring = coords[0] if coords else []
                
                # KML expects lon, lat (same as GeoJSON)
                kml_coords = [(c[0], c[1]) for c in outer_ring]
                
                pol = kml.newpolygon(name=f"Safe Zone {i+1}")
                pol.outerboundaryis = kml_coords
                pol.style.polystyle.color = simplekml.Color.rgb(50, 200, 50, 100)  # Semi-transparent green
                pol.style.polystyle.outline = 1
                pol.style.linestyle.color = simplekml.Color.green
                pol.style.linestyle.width = 2
                
                # Add description
                pol.description = f"""
                <![CDATA[
                <h3>Safe Grazing Zone {i+1}</h3>
                <p><b>Status:</b> Safe for grazing</p>
                <p><b>Criteria:</b> Good vegetation (NDVI > 0.3) and low population density</p>
                <p><b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
                ]]>
                """
        
        kml.save(str(output_file))
        print(f"✅ KML exported: {output_file}")
        return output_file
    
    def export_shapefile(self, ee_feature_collection, filename):
        """
        Export to Shapefile format (for QGIS and ArcGIS)
        
        Args:
            ee_feature_collection: Earth Engine FeatureCollection data (as dict)
            filename: Output filename (without extension)
        """
        output_file = self.output_dir / f"{filename}.shp"
        
        # Create shapefile writer
        w = shp.Writer(str(output_file))
        w.field('zone_id', 'N')
        w.field('quality', 'C', size=20)
        w.field('generated', 'C', size=20)
        
        features = ee_feature_collection.get('features', [])
        
        for i, feat in enumerate(features):
            geom = feat.get('geometry', {})
            geom_type = geom.get('type', '')
            coords = geom.get('coordinates', [])
            
            if geom_type == 'Polygon' and coords:
                # Extract outer ring
                outer_ring = coords[0] if coords else []
                
                # Shapefile expects lon, lat pairs
                shp_coords = [(c[0], c[1]) for c in outer_ring]
                
                w.poly([shp_coords])
                w.record(i+1, 'Good', datetime.now().strftime('%Y-%m-%d'))
        
        w.close()
        print(f"✅ Shapefile exported: {output_file}")
        
        # Also create .prj file with WGS84 projection
        prj_file = self.output_dir / f"{filename}.prj"
        with open(prj_file, 'w') as f:
            f.write('GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]')
        
        return output_file
    
    def export_coordinates_csv(self, ee_feature_collection, filename):
        """
        Export zone centroids and boundaries to CSV (for SMS alerts and mobile apps)
        
        Args:
            ee_feature_collection: Earth Engine FeatureCollection data (as dict)
            filename: Output filename (without extension)
        """
        output_file = self.output_dir / f"{filename}_coordinates.csv"
        
        features = ee_feature_collection.get('features', [])
        
        with open(output_file, 'w') as f:
            # Write header
            f.write("zone_id,centroid_lat,centroid_lon,boundary_points,quality,area_approx_km2\n")
            
            for i, feat in enumerate(features):
                geom = feat.get('geometry', {})
                coords = geom.get('coordinates', [])
                
                if coords:
                    # Get outer ring
                    outer_ring = coords[0] if coords else []
                    
                    # Calculate centroid (simple average)
                    if outer_ring:
                        avg_lon = sum(c[0] for c in outer_ring) / len(outer_ring)
                        avg_lat = sum(c[1] for c in outer_ring) / len(outer_ring)
                        
                        # Format boundary as semicolon-separated lat,lon pairs
                        boundary_str = ";".join([f"{c[1]:.6f},{c[0]:.6f}" for c in outer_ring[:10]])  # First 10 points
                        
                        # Rough area calculation (very approximate)
                        area_approx = len(outer_ring) * 0.01  # Placeholder
                        
                        f.write(f"{i+1},{avg_lat:.6f},{avg_lon:.6f},\"{boundary_str}\",Good,{area_approx:.2f}\n")
        
        print(f"✅ Coordinates CSV exported: {output_file}")
        return output_file
    
    def export_all_formats(self, ee_feature_collection, base_filename):
        """
        Export to all formats at once
        
        Args:
            ee_feature_collection: Earth Engine FeatureCollection data (as dict)
            base_filename: Base filename for all outputs
        
        Returns:
            Dictionary with paths to all generated files
        """
        print(f"\n📦 Exporting '{base_filename}' in multiple formats...")
        
        outputs = {
            'geojson': self.export_geojson(ee_feature_collection, base_filename),
            'kml': self.export_kml(ee_feature_collection, base_filename),
            'shapefile': self.export_shapefile(ee_feature_collection, base_filename),
            'csv': self.export_coordinates_csv(ee_feature_collection, base_filename)
        }
        
        print(f"\n✅ All formats exported successfully!")
        print(f"   📂 Output directory: {self.output_dir}")
        
        return outputs


if __name__ == "__main__":
    # Test with sample data
    sample_data = {
        'type': 'FeatureCollection',
        'features': [
            {
                'type': 'Feature',
                'geometry': {
                    'type': 'Polygon',
                    'coordinates': [[
                        [40.5, 0.5],
                        [40.6, 0.5],
                        [40.6, 0.6],
                        [40.5, 0.6],
                        [40.5, 0.5]
                    ]]
                },
                'properties': {'zone': 1}
            }
        ]
    }
    
    engine = GeofencingEngine(Path(__file__).parent / "OUTPUT")
    engine.export_all_formats(sample_data, 'test_zones')
    print("\n✅ Test completed")
