<?xml version="1.0" ?>
<sld:StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:sld="http://www.opengis.net/sld">
    <sld:UserLayer>
        <sld:LayerFeatureConstraints>
            <sld:FeatureTypeConstraint/>
        </sld:LayerFeatureConstraints>
        <sld:UserStyle>
            <sld:Name>ken_ppp_2019_AdjToCensus_u16bit_v2</sld:Name>
            <sld:Description>Generated by SLD4raster - https://cbsuygulama.wordpress.com/sld4raster</sld:Description>
            <sld:Title/>
            <sld:FeatureTypeStyle>
                <sld:Name/>
                <sld:Rule>
                    <sld:RasterSymbolizer>
                        <sld:Geometry>
                            <ogc:PropertyName>grid</ogc:PropertyName>
                        </sld:Geometry>
                        <sld:Opacity>1</sld:Opacity>
                        <sld:ColorMap type="intervals">
                            <sld:ColorMapEntry color="#fef0d9" label="&lt;= 1" opacity="1.0" quantity="1"/>
                            <sld:ColorMapEntry color="#fedcac" label="1-2" opacity="1.0" quantity="2"/>
                            <sld:ColorMapEntry color="#fdc383" label="2-3" opacity="1.0" quantity="3"/>
                            <sld:ColorMapEntry color="#fd9f67" label="3-4" opacity="1.0" quantity="4"/>
                            <sld:ColorMapEntry color="#f57a4e" label="4-8" opacity="1.0" quantity="8"/>
                            <sld:ColorMapEntry color="#e75338" label="8-10" opacity="1.0" quantity="10"/>
                            <sld:ColorMapEntry color="#cf2a1d" label="10-50" opacity="1.0" quantity="50"/>
                            <sld:ColorMapEntry color="#b30000" label="&gt;50" opacity="1.0" quantity="18545"/>
                        </sld:ColorMap>
                    </sld:RasterSymbolizer>
                </sld:Rule>
            </sld:FeatureTypeStyle>
        </sld:UserStyle>
    </sld:UserLayer>
</sld:StyledLayerDescriptor>